image: Visual Studio 2017

environment:
  nodejs_version: "8"

branches:
  only:
    - master
    - develop
    - /release/.*/
    - /hotfix/.*/
    - /feature/.*/

install:
  - choco install gitversion.portable -pre -y
  - ps: Install-Product node $env:nodejs_version
  - npm install source/Jobbr.Dashboard.Frontend/jobbr-dashboard --prefix source/Jobbr.Dashboard.Frontend/jobbr-dashboard

assembly_info:
  patch: false

before_build:
  - nuget restore source/Jobbr.Dashboard.sln
  - ps: C:\ProgramData\chocolatey\lib\GitVersion.Portable\tools\GitVersion.exe /l console /output buildserver /updateAssemblyInfo

platform: Any CPU
configuration: Release

build:
  parallel: true 
  project: source/Jobbr.Dashboard.sln

test: off

after_build:
  - cmd: cd source\Jobbr.Dashboard.Frontend\jobbr-dashboard & au build
  - cmd: nuget install ILMerge -ExcludeVersion
  - cmd: mkdir ilmerged
  - cmd: ILMerge\tools\ILMerge.exe /out:ilmerged/Jobbr.Dashboard.Backend.dll source/Jobbr.Dashboard.Backend/bin/Release/*.dll /target:library /targetplatform:v4,C:\Windows\Microsoft.NET\Framework64\v4.0.30319 /wildcards /internalize:internalize_exclude.txt /allowDup:HttpRequestMessageExtensions /allowDup:MediaTypeFormatterExtensions
  - cmd: nuget pack Jobbr.Dashboard.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%" -Symbols
  - cmd: appveyor PushArtifact "Jobbr.Dashboard.%GitVersion_NuGetVersion%.nupkg"
  - cmd: appveyor PushArtifact "Jobbr.Dashboard.%GitVersion_NuGetVersion%.symbols.nupkg"

deploy:
- provider: NuGet
  server: https://nuget.org
  api_key:
    secure: +AgExDSzPqydFKSbpQBS0j3s8d3rwTli8aRmMbUZ3DVBL29Lj7MNPOxEDLJT7f07
  on:
    appveyor_repo_tag: true